apiVersion: v1
kind: Secret
metadata:
  name: database-user
type: Opaque
data:
  database-user: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: database-password
type: Opaque
data:
  database-password: dGVzdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: database-name
type: Opaque
data:
  database-name: ZGVqYXZ1