version: '3.9'
services:
  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - 9090:9090
    volumes:
      - ./provisioning/prometheus/prometheus_config_docker.yml:/etc/prometheus/prometheus.yml
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--web.console.libraries=/usr/share/prometheus/console_libraries",
        "--web.console.templates=/usr/share/prometheus/consoles",
        "--storage.tsdb.retention.size=5GB"
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway" # To allow it to work on Linux
  grafana:
    build:
      context: ./provisioning/
      dockerfile: ./grafana/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  mite:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9301:9301
    depends_on:
      - prometheus
